# Generated by Django 4.2.22 on 2025-06-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story',
            field=models.FileField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
