# Generated by Django 4.2.22 on 2025-06-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
    ]
