# Generated by Django 4.2.22 on 2025-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_comment_productreview_review_and_more'),
        ('accounts', '0002_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_products',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='products.productvariant'),
        ),
    ]
