# Generated by Django 5.2.1 on 2025-05-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
